// sprites.js - Pixel Dragon Sprite Data
// Each sprite is a 2D array of hex color strings (null = transparent)
// Pixel scale: each entry = 1 logical pixel, rendered at PIXEL_SIZE x PIXEL_SIZE

// Color palette
const COLORS = {
  // Fire Dragon (Charmander style)
  FIRE_BODY: '#FF9800',
  FIRE_BELLY: '#FFF59D',
  FIRE_WING: '#FFB74D',
  FIRE_WING_TRANS: 'rgba(255,183,77,0.6)',
  // Ice Dragon (blue)
  ICE_BODY: '#4FC3F7',
  ICE_BELLY: '#E0F7FA',
  ICE_WING: '#81D4FA',
  ICE_WING_TRANS: 'rgba(129,212,250,0.6)',
  // Dark Dragon (purple)
  DARK_BODY: '#9575CD',
  DARK_BELLY: '#E1BEE7',
  DARK_WING: '#B39DDB',
  DARK_WING_TRANS: 'rgba(179,157,219,0.6)',
  // Gold Dragon
  GOLD_BODY: '#FFCA28',
  GOLD_BELLY: '#FFF9C4',
  GOLD_WING: '#FFE082',
  GOLD_WING_TRANS: 'rgba(255,224,130,0.6)',
  // Common
  EYE_WHITE: '#FFFFFF',
  EYE_BLACK: '#212121',
  EYE_HIGHLIGHT: '#FFFFFF',
  HORN: '#FFA726',
  HORN_DARK: '#FF9800',
  CLAW: '#BCAAA4',
  FIRE_RED: '#F44336',
  FIRE_ORANGE: '#FF9800',
  FIRE_YELLOW: '#FFEB3B',
  FIRE_CORE: '#FFFFFF',
  MOUTH: '#E53935',
  CHEEK: 'rgba(244,143,177,0.8)',
};

// Palette mapping per dragon type
const DRAGON_PALETTES = {
  fire: {
    body: COLORS.FIRE_BODY, belly: COLORS.FIRE_BELLY,
    wing: COLORS.FIRE_WING, wingTrans: COLORS.FIRE_WING_TRANS, horn: COLORS.FIRE_BODY,
  },
  ice: {
    body: COLORS.ICE_BODY, belly: COLORS.ICE_BELLY,
    wing: COLORS.ICE_WING, wingTrans: COLORS.ICE_WING_TRANS, horn: '#29B6F6',
  },
  dark: {
    body: COLORS.DARK_BODY, belly: COLORS.DARK_BELLY,
    wing: COLORS.DARK_WING, wingTrans: COLORS.DARK_WING_TRANS, horn: '#7E57C2',
  },
  gold: {
    body: COLORS.GOLD_BODY, belly: COLORS.GOLD_BELLY,
    wing: COLORS.GOLD_WING, wingTrans: COLORS.GOLD_WING_TRANS, horn: '#FFB300',
  },
};

// Helper: shorthand notation for building sprites
const SHORTHAND = {
  'b': 'body', 'e': 'belly', 'w': 'wing',
  'k': 'eyeBlack', 'W': 'eyeWhite',
  'h': 'horn', 'c': 'claw', 'm': 'mouth', 'p': 'cheek',
  'n': 'eyeBlack', 'z': 'eyeWhite',
  '.': null, ' ': null,
};

function parseSprite(grid, palette) {
  return grid.map(row => row.map(ch => {
    if (ch === '.' || ch === ' ') return null;
    const key = SHORTHAND[ch];
    if (!key) return null;
    return palette[key] || COLORS[key] || null;
  }));
}

// === SPRITE FRAMES ===
// 16x16 grid sprites
const SPRITE_DATA = {
  idle: [
    [
      '................',
      '....hh....hh....',
      '...bbbbbbbbbb...',
      '..bbbbbbbbbbbb..',
      '..bbWkbbbbWkbb..',
      '..bbbbbbbbbbbb..',
      '...bpbbbbbbpb...',
      '....bbbbbbbb....',
      '.....beeeeb.....',
      '.ww.cbeeeebc.ww.',
      '.ww..beeeeb..ww.',
      '.....beeeeb.....',
      '.....bb..bb.....',
      '....cc....cc....',
      '................',
      '................',
    ],
    [
      '................',
      '................',
      '....hh....hh....',
      '...bbbbbbbbbb...',
      '..bbbbbbbbbbbb..',
      '..bbWkbbbbWkbb..',
      '..bbbbbbbbbbbb..',
      '...bpbbbbbbpb...',
      '....bbbbbbbb....',
      '.....beeeeb.....',
      '.ww.cbeeeebc.ww.',
      '.ww..beeeeb..ww.',
      '.....beeeeb.....',
      '.....bb..bb.....',
      '....cc....cc....',
      '................',
    ],
    [
      '................',
      '....hh....hh....',
      '...bbbbbbbbbb...',
      '..bbbbbbbbbbbb..',
      '..bbWkbbbbWkbb..',
      '..bbbbbbbbbbbb..',
      '...bpbbbbbbpb...',
      '....bbbbbbbb....',
      '.....beeeeb.....',
      '.ww.cbeeeebc.ww.',
      '.ww..beeeeb..ww.',
      '.....beeeeb.....',
      '.....bb..bb.....',
      '....cc....cc....',
      '................',
      '................',
    ],
    [
      '................',
      '................',
      '....hh....hh....',
      '...bbbbbbbbbb...',
      '..bbbbbbbbbbbb..',
      '..bbWkbbbbWkbb..',
      '..bbbbbbbbbbbb..',
      '...bpbbbbbbpb...',
      '....bbbbbbbb....',
      '.ww..beeeeb..ww.',
      '.ww.cbeeeebc.ww.',
      '.....beeeeb.....',
      '.....bb..bb.....',
      '....cc....cc....',
      '................',
      '................',
    ],
  ],

  walk: [
    [
      '................',
      '....hh....hh....',
      '...bbbbbbbbbb...',
      '..bbbbbbbbbbbb..',
      '..bbWkbbbbWkbb..',
      '..bbbbbbbbbbbb..',
      '...bpbbbbbbpb...',
      '....bbbbbbbb....',
      '.....beeeeb.....',
      '.ww.cbeeeebc.ww.',
      '.ww..beeeeb..ww.',
      '.....beeeeb.....',
      '.....bb.........',
      '....cc...cc.....',
      '..........bb....',
      '................',
    ],
    [
      '................',
      '....hh....hh....',
      '...bbbbbbbbbb...',
      '..bbbbbbbbbbbb..',
      '..bbWkbbbbWkbb..',
      '..bbbbbbbbbbbb..',
      '...bpbbbbbbpb...',
      '....bbbbbbbb....',
      '.....beeeeb.....',
      '.ww.cbeeeebc.ww.',
      '.ww..beeeeb..ww.',
      '.....beeeeb.....',
      '.....bb..bb.....',
      '....cc....cc....',
      '................',
      '................',
    ],
    [
      '................',
      '....hh....hh....',
      '...bbbbbbbbbb...',
      '..bbbbbbbbbbbb..',
      '..bbWkbbbbWkbb..',
      '..bbbbbbbbbbbb..',
      '...bpbbbbbbpb...',
      '....bbbbbbbb....',
      '.....beeeeb.....',
      '.ww.cbeeeebc.ww.',
      '.ww..beeeeb..ww.',
      '.....beeeeb.....',
      '.........bb.....',
      '.....cc...cc....',
      '....bb..........',
      '................',
    ],
    [
      '................',
      '....hh....hh....',
      '...bbbbbbbbbb...',
      '..bbbbbbbbbbbb..',
      '..bbWkbbbbWkbb..',
      '..bbbbbbbbbbbb..',
      '...bpbbbbbbpb...',
      '....bbbbbbbb....',
      '.....beeeeb.....',
      '.ww.cbeeeebc.ww.',
      '.ww..beeeeb..ww.',
      '.....beeeeb.....',
      '.....bb..bb.....',
      '....cc....cc....',
      '................',
      '................',
    ],
    [
      '................',
      '................',
      '....hh....hh....',
      '...bbbbbbbbbb...',
      '..bbbbbbbbbbbb..',
      '..bbWkbbbbWkbb..',
      '..bbbbbbbbbbbb..',
      '...bpbbbbbbpb...',
      '....bbbbbbbb....',
      '.....beeeeb.....',
      '.ww.cbeeeebc.ww.',
      '.ww..beeeeb..ww.',
      '.....beeeeb.....',
      '.....bb..bb.....',
      '....cc....cc....',
      '................',
    ],
    [
      '................',
      '....hh....hh....',
      '...bbbbbbbbbb...',
      '..bbbbbbbbbbbb..',
      '..bbWkbbbbWkbb..',
      '..bbbbbbbbbbbb..',
      '...bpbbbbbbpb...',
      '....bbbbbbbb....',
      '.....beeeeb.....',
      '.ww.cbeeeebc.ww.',
      '.ww..beeeeb..ww.',
      '.....beeeeb.....',
      '.....bb..bb.....',
      '....cc....cc....',
      '................',
      '................',
    ],
  ],

  sleep: [
    [
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '....hh..........',
      '...bbbb.........',
      '..bbbbbb........',
      '..bbkkbb...ww...',
      '..bbbbbbbbbeebbb',
      '...bpbbbeeeeebbb',
      '....bbbbbbbeebb.',
      '.....cccc.ccc...',
      '................',
    ],
    [
      '................',
      '................',
      '................',
      '..........z.....',
      '.........z......',
      '.......z........',
      '................',
      '....hh..........',
      '...bbbb.........',
      '..bbbbbb........',
      '..bbkkbb...ww...',
      '..bbbbbbbbbeebbb',
      '...bpbbbeeeeebbb',
      '....bbbbbbbeebb.',
      '.....cccc.ccc...',
      '................',
    ],
    [
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '....hh..........',
      '...bbbb.........',
      '..bbbbbb........',
      '..bbkkbb...ww...',
      '..bbbbbbbbbeebbb',
      '...bpbbbeeeeebbb',
      '....bbbbbbbeebb.',
      '.....cccc.ccc...',
      '................',
    ],
    [
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '....hh..........',
      '...bbbb.........',
      '..bbbbbb........',
      '..bbkkbb...ww...',
      '..bbbbbbbbbeebbb',
      '...bpbbbeeeeebbb',
      '....bbbbbbbeebb.',
      '.....cccc.ccc...',
      '................',
    ],
  ],

  eat: [
    [
      '................',
      '....hh....hh....',
      '...bbbbbbbbbb...',
      '..bbbbbbbbbbbb..',
      '..bbWkbbbbWkbb..',
      '..bbbbbbbbbbbb..',
      '...bpbbbbbbpb...',
      '....bbmmmmbb....',
      '.....beeeeb.....',
      '.ww.cbeeeebc.ww.',
      '.ww..beeeeb..ww.',
      '.....beeeeb.....',
      '.....bb..bb.....',
      '....cc....cc....',
      '................',
      '................',
    ],
    [
      '................',
      '....hh....hh....',
      '...bbbbbbbbbb...',
      '..bbbbbbbbbbbb..',
      '..bbWkbbbbWkbb..',
      '..bbbbbbbbbbbb..',
      '...bpbbbbbbpb...',
      '....bbbbbbbb....',
      '.....beeeeb.....',
      '.ww.cbeeeebc.ww.',
      '.ww..beeeeb..ww.',
      '.....beeeeb.....',
      '.....bb..bb.....',
      '....cc....cc....',
      '................',
      '................',
    ],
    [
      '................',
      '....hh....hh....',
      '...bbbbbbbbbb...',
      '..bbbbbbbbbbbb..',
      '..bbWkbbbbWkbb..',
      '..bbbbbbbbbbbb..',
      '...bpbbbbbbpb...',
      '....bbmmmmbb....',
      '.....beeeeb.....',
      '.ww.cbeeeebc.ww.',
      '.ww..beeeeb..ww.',
      '.....beeeeb.....',
      '.....bb..bb.....',
      '....cc....cc....',
      '................',
      '................',
    ],
    [
      '................',
      '....hh....hh....',
      '...bbbbbbbbbb...',
      '..bbbbbbbbbbbb..',
      '..bbnbbbbbbnbb..',
      '..bbbbbbbbbbbb..',
      '...bpbbbbbbpb...',
      '....bbbbbbbb....',
      '.....beeeeb.....',
      '.ww.cbeeeebc.ww.',
      '.ww..beeeeb..ww.',
      '.....beeeeb.....',
      '.....bb..bb.....',
      '....cc....cc....',
      '................',
      '................',
    ],
  ],

  play: [
    [
      '................',
      '................',
      '................',
      '....hh....hh....',
      '...bbbbbbbbbb...',
      '..bbbbbbbbbbbb..',
      '..bbWkbbbbWkbb..',
      '..bbbbbbbbbbbb..',
      '...bpbbbbbbpb...',
      '....bbbbbbbb....',
      '.ww.cbeeeebc.ww.',
      '.ww..beeeeb..ww.',
      '....cbb..bbc....',
      '................',
      '................',
      '................',
    ],
    [
      '....hh....hh....',
      '...bbbbbbbbbb...',
      '..bbbbbbbbbbbb..',
      '..bbWkbbbbWkbb..',
      '..bbbbbbbbbbbb..',
      '...bpbbbbbbpb...',
      '....bbmmmmbb....',
      '.....beeeeb.....',
      '.ww.cbeeeebc.ww.',
      '.ww..beeeeb..ww.',
      '.....beeeeb.....',
      '.....bb..bb.....',
      '....cc....cc....',
      '................',
      '................',
      '................',
    ],
    [
      '....hh....hh....',
      '...bbbbbbbbbb...',
      '..bbbbbbbbbbbb..',
      '..bbWkbbbbWkbb..',
      '..bbbbbbbbbbbb..',
      '...bpbbbbbbpb...',
      '....bbmmmmbb....',
      '.....beeeeb.....',
      '.ww.cbeeeebc.ww.',
      '.ww..beeeeb..ww.',
      '.....beeeeb.....',
      '.....bb..bb.....',
      '....cc....cc....',
      '................',
      '................',
      '................',
    ],
    [
      '................',
      '....hh....hh....',
      '...bbbbbbbbbb...',
      '..bbbbbbbbbbbb..',
      '..bbWkbbbbWkbb..',
      '..bbbbbbbbbbbb..',
      '...bpbbbbbbpb...',
      '....bbbbbbbb....',
      '.ww..beeeeb..ww.',
      '.ww.cbeeeebc.ww.',
      '.....beeeeb.....',
      '.....bb..bb.....',
      '....cc....cc....',
      '................',
      '................',
      '................',
    ],
    [
      '................',
      '................',
      '....hh....hh....',
      '...bbbbbbbbbb...',
      '..bbbbbbbbbbbb..',
      '..bbWkbbbbWkbb..',
      '..bbbbbbbbbbbb..',
      '...bpbbbbbbpb...',
      '....bbbbbbbb....',
      '.....beeeeb.....',
      '.ww.cbeeeebc.ww.',
      '.ww..beeeeb..ww.',
      '.....beeeeb.....',
      '.....bb..bb.....',
      '....cc....cc....',
      '................',
    ],
    [
      '................',
      '....hh....hh....',
      '...bbbbbbbbbb...',
      '..bbbbbbbbbbbb..',
      '..bbWkbbbbWkbb..',
      '..bbbbbbbbbbbb..',
      '...bpbbbbbbpb...',
      '....bbbbbbbb....',
      '.....beeeeb.....',
      '.ww.cbeeeebc.ww.',
      '.ww..beeeeb..ww.',
      '.....beeeeb.....',
      '.....bb..bb.....',
      '....cc....cc....',
      '................',
      '................',
    ],
  ],

  fly: [
    [
      '.ww..........ww.',
      '..ww........ww..',
      '...ww......ww...',
      '....hh....hh....',
      '...bbbbbbbbbb...',
      '..bbbbbbbbbbbb..',
      '..bbWkbbbbWkbb..',
      '..bbbbbbbbbbbb..',
      '...bpbbbbbbpb...',
      '....bbbbbbbb....',
      '.....beeeeb.....',
      '....cbeeeebc....',
      '.....beeeeb.....',
      '.....bb..bb.....',
      '....cc....cc....',
      '................',
    ],
    [
      '................',
      '................',
      '...ww......ww...',
      '....hh....hh....',
      '..wwbbbbbbbbww..',
      '.wwbbbbbbbbbbww.',
      '..bbWkbbbbWkbb..',
      '..bbbbbbbbbbbb..',
      '...bpbbbbbbpb...',
      '....bbbbbbbb....',
      '.....beeeeb.....',
      '....cbeeeebc....',
      '.....beeeeb.....',
      '.....bb..bb.....',
      '....cc....cc....',
      '................',
    ],
    [
      '................',
      '................',
      '................',
      '....hh....hh....',
      '...bbbbbbbbbb...',
      '..bbbbbbbbbbbb..',
      '..bbWkbbbbWkbb..',
      '..bbbbbbbbbbbb..',
      '...bpbbbbbbpb...',
      '....bbbbbbbb....',
      '.ww..beeeeb..ww.',
      'ww..cbeeeebc..ww',
      'ww...beeeeb...ww',
      '.....bb..bb.....',
      '....cc....cc....',
      '................',
    ],
    [
      '................',
      '................',
      '...ww......ww...',
      '....hh....hh....',
      '..wwbbbbbbbbww..',
      '.wwbbbbbbbbbbww.',
      '..bbWkbbbbWkbb..',
      '..bbbbbbbbbbbb..',
      '...bpbbbbbbpb...',
      '....bbbbbbbb....',
      '.....beeeeb.....',
      '....cbeeeebc....',
      '.....beeeeb.....',
      '.....bb..bb.....',
      '....cc....cc....',
      '................',
    ],
    [
      '.ww..........ww.',
      '..ww........ww..',
      '...ww......ww...',
      '....hh....hh....',
      '...bbbbbbbbbb...',
      '..bbbbbbbbbbbb..',
      '..bbWkbbbbWkbb..',
      '..bbbbbbbbbbbb..',
      '...bpbbbbbbpb...',
      '....bbbbbbbb....',
      '.....beeeeb.....',
      '....cbeeeebc....',
      '.....beeeeb.....',
      '.....bb..bb.....',
      '....cc....cc....',
      '................',
    ],
    [
      '................',
      '.ww..........ww.',
      '..ww........ww..',
      '....hh....hh....',
      '...bbbbbbbbbb...',
      '..bbbbbbbbbbbb..',
      '..bbWkbbbbWkbb..',
      '..bbbbbbbbbbbb..',
      '...bpbbbbbbpb...',
      '....bbbbbbbb....',
      '.....beeeeb.....',
      '....cbeeeebc....',
      '.....beeeeb.....',
      '.....bb..bb.....',
      '....cc....cc....',
      '................',
    ],
  ],

  fire: [
    [
      '................',
      '....hh....hh....',
      '...bbbbbbbbbb...',
      '..bbbbbbbbbbbb..',
      '..bbnbbbbbbnbb..',
      '..bbbbbbbbbbbb..',
      '...bpbbbbbbpb...',
      '....bbmmmmbb....',
      '.....beeeeb.....',
      '.ww.cbeeeebc.ww.',
      '.ww..beeeeb..ww.',
      '.....beeeeb.....',
      '.....bb..bb.....',
      '....cc....cc....',
      '................',
      '................',
    ],
    [
      '................',
      '....hh....hh....',
      '...bbbbbbbbbb...',
      '..bbbbbbbbbbbb..',
      '..bbnbbbbbbnbb..',
      '..bbbbbbbbbbbb..',
      '...bpbbbbbbpb...',
      '....bbmmmmbb....',
      '.....beeeeb.....',
      '.ww.cbeeeebc.ww.',
      '.ww..beeeeb..ww.',
      '.....beeeeb.....',
      '.....bb..bb.....',
      '....cc....cc....',
      '................',
      '................',
    ],
    [
      '................',
      '....hh....hh....',
      '...bbbbbbbbbb...',
      '..bbbbbbbbbbbb..',
      '..bbWkbbbbWkbb..',
      '..bbbbbbbbbbbb..',
      '...bpbbbbbbpb...',
      '....bbmmmmbb....',
      '.....beeeebFF...',
      '.ww.cbeeeebOFF..',
      '.ww..beeeeb..ww.',
      '.....beeeeb.....',
      '.....bb..bb.....',
      '....cc....cc....',
      '................',
      '................',
    ],
    [
      '................',
      '....hh....hh....',
      '...bbbbbbbbbb...',
      '..bbbbbbbbbbbb..',
      '..bbWkbbbbWkbb..',
      '..bbbbbbbbbbbb..',
      '...bpbbbbbbpb...',
      '....bbmmmmbb....',
      '.....beeeebFF...',
      '.ww.cbeeeebOFF..',
      '.ww..beeeebYOF..',
      '.....beeeebFF...',
      '.....bb..bb.....',
      '....cc....cc....',
      '................',
      '................',
    ],
    [
      '................',
      '....hh....hh....',
      '...bbbbbbbbbb...',
      '..bbbbbbbbbbbb..',
      '..bbWkbbbbWkbb..',
      '..bbbbbbbbbbbb..',
      '...bpbbbbbbpb...',
      '....bbmmmmbb....',
      '.....beeeebFF...',
      '.ww.cbeeeebOFF..',
      '.ww..beeeebYOF..',
      '.....beeeebFF...',
      '.....bb..bb.....',
      '....cc....cc....',
      '................',
      '................',
    ],
    [
      '................',
      '....hh....hh....',
      '...bbbbbbbbbb...',
      '..bbbbbbbbbbbb..',
      '..bbWkbbbbWkbb..',
      '..bbbbbbbbbbbb..',
      '...bpbbbbbbpb...',
      '....bbmmmmbb....',
      '.....beeeebFF...',
      '.ww.cbeeeebOFF..',
      '.ww..beeeeb..ww.',
      '.....beeeeb.....',
      '.....bb..bb.....',
      '....cc....cc....',
      '................',
      '................',
    ],
  ],

  happy: [
    [
      '................',
      '....hh....hh....',
      '...bbbbbbbbbb...',
      '..bbbbbbbbbbbb..',
      '..bbnbbbbbbnbb..',
      '..bbbbbbbbbbbb..',
      '...bpbbbbbbpb...',
      '....bbbbbbbb....',
      '.....beeeeb.....',
      '.ww.cbeeeebc.ww.',
      '.ww..beeeeb..ww.',
      '.....beeeeb.....',
      '.....bb..bb.....',
      '....cc....cc....',
      '................',
      '................',
    ],
    [
      '................',
      '................',
      '....hh....hh....',
      '...bbbbbbbbbb...',
      '..bbbbbbbbbbbb..',
      '..bbnbbbbbbnbb..',
      '..bbbbbbbbbbbb..',
      '...bpbbbbbbpb...',
      '....bbbbbbbb....',
      '.ww.cbeeeebc.ww.',
      '.ww..beeeeb..ww.',
      '.....beeeeb.....',
      '.....bb..bb.....',
      '....cc....cc....',
      '................',
      '................',
    ],
    [
      '....hh....hh....',
      '...bbbbbbbbbb...',
      '..bbbbbbbbbbbb..',
      '..bbnbbbbbbnbb..',
      '..bbbbbbbbbbbb..',
      '...bpbbbbbbpb...',
      '....bbbbbbbb....',
      '.....beeeeb.....',
      '.ww.cbeeeebc.ww.',
      '.ww..beeeeb..ww.',
      '.....beeeeb.....',
      '.....bb..bb.....',
      '....cc....cc....',
      '................',
      '................',
      '................',
    ],
    [
      '................',
      '....hh....hh....',
      '...bbbbbbbbbb...',
      '..bbbbbbbbbbbb..',
      '..bbnbbbbbbnbb..',
      '..bbbbbbbbbbbb..',
      '...bpbbbbbbpb...',
      '....bbbbbbbb....',
      '.....beeeeb.....',
      '.ww.cbeeeebc.ww.',
      '.ww..beeeeb..ww.',
      '.....beeeeb.....',
      '.....bb..bb.....',
      '....cc....cc....',
      '................',
      '................',
    ],
  ],
};
// Build the full palette map including special colors
function getFullPalette(dragonType) {
  const dp = DRAGON_PALETTES[dragonType] || DRAGON_PALETTES.fire;
  return {
    body: dp.body,
    belly: dp.belly,
    wing: dp.wing,
    wingTrans: dp.wingTrans,
    horn: dp.horn || COLORS.HORN,
    eyeBlack: COLORS.EYE_BLACK,
    eyeWhite: COLORS.EYE_WHITE,
    claw: COLORS.CLAW,
    mouth: COLORS.MOUTH,
    cheek: COLORS.CHEEK,
  };
}

// Parse all frames for a given dragon type
function getSprites(dragonType) {
  const palette = getFullPalette(dragonType);
  const result = {};
  for (const [action, frames] of Object.entries(SPRITE_DATA)) {
    result[action] = frames.map(frame => {
      return frame.map(row => {
        const chars = row.split('');
        return chars.map(ch => {
          if (ch === '.' || ch === ' ') return null;
          const key = SHORTHAND[ch];
          if (!key) {
            // Special fire colors
            if (ch === 'F') return COLORS.FIRE_RED;
            if (ch === 'O') return COLORS.FIRE_ORANGE;
            if (ch === 'Y') return COLORS.FIRE_YELLOW;
            if (ch === 'f') return COLORS.FIRE_CORE;
            return null;
          }
          return palette[key] || null;
        });
      });
    });
  }
  return result;
}

const ACCESSORIES = {
  crown: {
    name: '皇冠',
    frames: [[
      '................',
      '....cc..cc......',
      '....cc..cc......',
      '...cccccccc.....',
      '...cccccccc.....',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ]],
    color: '#FFD700',
  },
  wizard_hat: {
    name: '巫师帽',
    frames: [[
      '.......bb.......',
      '......bbbb......',
      '.....bbbbbb.....',
      '....bbbbbbbb....',
      '...bbbbbbbbbb...',
      '..cccccccccccc..',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ]],
    color: '#5C6BC0',
  },
  cowboy_hat: {
    name: '牛仔帽',
    frames: [[
      '................',
      '....bbbbbb......',
      '...bbbbbbbb.....',
      '..bbbbbbbbbb....',
      '.cccccccccccccc.',
      '.cccccccccccccc.',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ]],
    color: '#8D6E63',
  },
  flower_crown: {
    name: '花环',
    frames: [[
      '................',
      '..r.g.r.g.r....',
      '..g.r.g.r.g....',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ]],
    color: '#4CAF50',
    extraColors: { r: '#F44336', g: '#FFEB3B' },
  },
  red_scarf: {
    name: '红围巾',
    frames: [[
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '...rrrrrrrr....',
      '..rrrrrrrrrr...',
      '..rrrrrrrrrrr..',
      '...rrrrrrrr....',
      '................',
      '................',
      '................',
      '................',
      '................',
    ]],
    color: '#F44336',
  },
  rainbow_scarf: {
    name: '彩虹围巾',
    frames: [[
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '...rrggbbrr....',
      '..rrggbbrrrr...',
      '..rrggbbrrrrr..',
      '...rrggbbrr....',
      '................',
      '................',
      '................',
      '................',
      '................',
    ]],
    color: '#F44336',
    extraColors: { g: '#4CAF50', b: '#2196F3' },
  },
  butterfly_wings: {
    name: '蝴蝶翅膀',
    frames: [[
      '................',
      '................',
      '................',
      '................',
      '................',
      '.pp......pp.....',
      'pppp....pppp...',
      '.pppp..pppp....',
      '..pppppppp.....',
      '..pppppppp.....',
      '.pppp..pppp....',
      '.pp......pp....',
      '................',
      '................',
      '................',
      '................',
    ]],
    color: '#E040FB',
  },
  rocket_pack: {
    name: '火箭背包',
    frames: [[
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '...ss..ss.......',
      '...ss..ss.......',
      '...ss..ss.......',
      '...ss..ss.......',
      '...ff..ff.......',
      '...ff..ff.......',
      '................',
      '................',
      '................',
      '................',
    ]],
    color: '#78909C',
    extraColors: { f: '#FF9800' },
  },
  cape: {
    name: '小斗篷',
    frames: [[
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '..cccccccccc....',
      '.cccccccccccc...',
      '.cccccccccccc...',
      '..cccccccccc....',
      '...cccccccc.....',
      '...cccccccc.....',
      '....cccccc......',
      '................',
      '................',
    ]],
    color: '#B71C1C',
  },
};

function getAccessorySprite(accessoryId) {
  const acc = ACCESSORIES[accessoryId];
  if (!acc) return null;
  return acc.frames.map(frame =>
    frame.map(row =>
      row.split('').map(ch => {
        if (ch === '.' || ch === ' ') return null;
        if (acc.extraColors && acc.extraColors[ch]) return acc.extraColors[ch];
        return acc.color;
      })
    )
  );
}
